import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Helper function to check if a directory is empty
function isDirectoryEmpty(dirPath: string): boolean {
  try {
    const fullPath = path.resolve(__dirname, 'docs', dirPath); // Adjust to your 'docs' folder location
    return fs.existsSync(fullPath) && fs.readdirSync(fullPath).length === 0;
  } catch (err) {
    console.error(`Error checking directory: ${dirPath}`, err);
    return true; // Treat as empty if there's an error
  }
}

const sidebars: SidebarsConfig = {
  commandcenterSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: isDirectoryEmpty('command-center/overview')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/overview' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: isDirectoryEmpty('command-center/getting-started')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/getting-started' }],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: isDirectoryEmpty('command-center/user-guides')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/user-guides' }],
    },
    {
      type: 'category',
      label: 'Administration and Configuration',
      items: isDirectoryEmpty('command-center/administration')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/administration' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting and FAQs',
      items: isDirectoryEmpty('command-center/troubleshooting-faqs')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/troubleshooting-faqs' }],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: isDirectoryEmpty('command-center/release-notes')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'command-center/release-notes' }],
    },
  ],

  permitsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: isDirectoryEmpty('permits/overview')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/overview' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: isDirectoryEmpty('permits/getting-started')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/getting-started' }],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: isDirectoryEmpty('permits/user-guides')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/user-guides' }],
    },
    {
      type: 'category',
      label: 'Administration and Configuration',
      items: isDirectoryEmpty('permits/administration')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/administration' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting and FAQs',
      items: isDirectoryEmpty('permits/troubleshooting-faqs')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/troubleshooting-faqs' }],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: isDirectoryEmpty('permits/release-notes')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'permits/release-notes' }],
    },
  ],

  platesentrySidebar: [
    {
      type: 'category',
      label: 'Overview',
      items: isDirectoryEmpty('platesentry/overview')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/overview' }],
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: isDirectoryEmpty('platesentry/getting-started')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/getting-started' }],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: isDirectoryEmpty('platesentry/user-guides')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/user-guides' }],
    },
    {
      type: 'category',
      label: 'Administration and Configuration',
      items: isDirectoryEmpty('platesentry/administration')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/administration' }],
    },
    {
      type: 'category',
      label: 'Troubleshooting and FAQs',
      items: isDirectoryEmpty('platesentry/troubleshooting-faqs')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/troubleshooting-faqs' }],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: isDirectoryEmpty('platesentry/release-notes')
        ? [{ type: 'doc', id: 'placeholder' }]
        : [{ type: 'autogenerated', dirName: 'platesentry/release-notes' }],
    },
  ],

  module1Sidebar: isDirectoryEmpty('command-center/modules/module1')
    ? [{ type: 'doc', id: 'placeholder' }]
    : [
        {
          type: 'autogenerated',
          dirName: 'command-center/modules/module1',
        },
      ],

  module2Sidebar: isDirectoryEmpty('command-center/modules/module2')
    ? [{ type: 'doc', id: 'placeholder' }]
    : [
        {
          type: 'autogenerated',
          dirName: 'command-center/modules/module2',
        },
      ],
};

export default sidebars;
