import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  commandcenterSidebar: [
    {
      type: 'doc',
      id: 'command-center/overview', // Add the overview document directly
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started', // Custom label
      items: [
        {
          type: 'autogenerated',
          dirName: 'command-center/getting-started', // Autogenerate items within "getting-started"
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'command-center/user-guides', // Autogenerate items within "guides"
        },
      ],
    },
	{
      type: 'category',
      label: 'Administration and Configuration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'command-center/administration', // Autogenerate items within "release-notes"
        },
      ],
    },
	{
      type: 'category',
      label: 'Troubleshooting and FAQs',
      items: [
        {
          type: 'autogenerated',
          dirName: 'command-center/troubleshooting-faqs', // Autogenerate items within "release-notes"
        },
      ],
    },
	{
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'command-center/release-notes', // Autogenerate items within "release-notes"
        },
      ],
    },
  ],
  
    permitsSidebar: [
    {
      type: 'doc',
      id: 'permits/overview', // Add the overview document directly
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started', // Custom label
      items: [
        {
          type: 'autogenerated',
          dirName: 'permits/getting-started', // Autogenerate items within "getting-started"
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'permits/guides', // Autogenerate items within "guides"
        },
      ],
    },
	    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'permits/release-notes', // Autogenerate items within "release-notes"
        },
      ],
    },
  ],
  
  platesentrySidebar: [
    {
      type: 'doc',
      id: 'platesentry/overview', // Add the overview document directly
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Getting Started', // Custom label
      items: [
        {
          type: 'autogenerated',
          dirName: 'platesentry/getting-started', // Autogenerate items within "getting-started"
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'platesentry/guides', // Autogenerate items within "guides"
        },
      ],
    },
	    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'platesentry/release-notes', // Autogenerate items within "release-notes"
        },
      ],
    },
  ],
  
  module1Sidebar: [
    {
      type: 'autogenerated',
	  dirName: 'command-center/modules/module1', // Autogenerate items within "module1"
    },
  ],
  
    module2Sidebar: [
    {
      type: 'autogenerated',
	  dirName: 'command-center/modules/module2', // Autogenerate items within "module2"
    },
  ],
  
};

export default sidebars;
